service: markito
image: paganotoni/markito
servers:
  web:
    hosts:
      - 178.156.136.27
    options:
      "add-host": host.docker.internal:host-gateway
    labels:
      traefik.http.routers.markito.rule: "Host(`markito.antoniopagano.com`)"
      traefik.http.routers.markito_secure.rule: "Host(`markito.antoniopagano.com`)"
      traefik.http.routers.markito_secure.entrypoints: websecure
      traefik.http.routers.markito_secure.tls: true
      traefik.http.routers.markito_secure.tls.certresolver: letsencrypt

volumes:
  - /data/markito:/data/markito

registry:
  server: ghcr.io
  username: paganotoni
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    GO_ENV: production
    PORT: 80
    DATABASE_URL: /data/markito/database.db
  secret:
    - SESSION_SECRET
    - SESSION_NAME

healthcheck:
  cmd: wget -qO- http://localhost/health
  max_attempts: 3

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "antonio@pagano.id"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
