service: markito
image: paganotoni/markito
servers:
  - <%= ENV["PRODUCTION_SERVER_IP"] %>

volumes:
  - /data/markito:/data/markito

registry:
  server: ghcr.io
  username: paganotoni
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    GO_ENV: production
    DATABASE_URL: /data/markito/database.db
    BASE_URL: "https://markito.antoniopagano.com"
  secret:
    - SESSION_SECRET
    - SESSION_NAME

proxy:
  host: markito.antoniopagano.com
  ssl: true
  app_port: 3000
  forward_headers: true
  healthcheck:
    interval: 2
    timeout: 2
    path: /health

builder:
  arch: amd64
  cache:
    type: gha
