service: markito
image: paganotoni/markito
servers:
  web:
    hosts:
      - <%= ENV["PRODUCTION_SERVER_IP"] %>
    options:
      cpus: 0.5

volumes:
  - /data/markito:/data/markito

registry:
  server: "localhost:5555"

env:
  clear:
    GO_ENV: production
    DATABASE_URL: /data/markito/database.db
    BASE_URL: "https://markito.antoniopagano.com"
  secret:
    - SESSION_SECRET
    - SESSION_NAME

proxy:
  host: markito.antoniopagano.com
  ssl: true
  app_port: 3000
  forward_headers: true
  healthcheck:
    interval: 2
    timeout: 2
    path: /health

builder:
  arch: amd64
  cache:
    type: gha
